services:
  app:
    container_name: fatec-api-container
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASS: f@tec
      API_KEY: restaurant-api-key
      JWT_SECRET: f@tec
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASS: admin
      DATABASE_NAME: restaurant_api
    networks:
      - fatec-network
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:14-alpine
    container_name: fatec-postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restaurant_api
      POSTGRES_USER: postgres
    networks:
      - fatec-network
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  fatec-network:
    driver: bridge