services:
  app:
    container_name: fatec-api-container
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASS: f@tec
      API_KEY: restaurant-api-key
      JWT_SECRET: f@tec
      DATABASE_HOST: db # O nome do serviço do banco de dados no Docker Compose
      DATABASE_PORT: 5432
      DATABASE_USER: postgres # Corrigido para o usuário que o Postgres cria
      DATABASE_PASS: admin # A senha definida em POSTGRES_PASSWORD
      DATABASE_NAME: restaurant_api # Corrigido para o nome do banco de dados
    networks:
      - fatec-network

  db:
    image: postgres:14-alpine
    container_name: fatec-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restaurant_api # O nome do banco de dados que será criado
      POSTGRES_USER: postgres # O usuário padrão do PostgreSQL
    networks:
      - fatec-network

volumes:
  pgdata:

networks:
  fatec-network:
    driver: bridge